export const GET_LIST_CART = "[CART] GET LIST CART";
export const ADD_TO_CART = "[CART] ADD TO CART";
export const UPDATE_CART_LIST = "[CART] UPDATE CART LIST";
export const REMOVE_FROM_CART = "[CART] REMOVE FROM CART";
