export const GET_LIST_KATEGORI = "GET LIST KATEGORI";
export const ADD_KATEGORI = "ADD KATEGORI";
export const GET_KATEGORI_BY_ID = "GET KATEGORI BY ID";
export const UPDATE_KATEGORI = "UPDATE KATEGORI";
export const DELETE_KATEGORI = "DELETE KATEGORI";
